### PR TITLE
IHLU integration

### PR DESCRIPTION
**Pull request by torurstrom**

### CODE REVIEW

**Comment by jeuneS2** [comment]
Should the changes to jembench really be in there, or are they leftovers
from development/debugging?

**Comment by torurstrom** [comment]
The jembench files add a better locking test, but if the benchmark should
be kept according to the standard then they shouldn't be included.

**Comment by schoeberl** [comment]
Please keep the benchmarks as they are. They are somehow 'official'.
A change needs some more coordination and a new version number.

Could you also please keep the Makefile as in the original master.
We shall keep the defaults as they are. Probably we should also
have this include like in Patmos for local default changes.

Why is invalCache gone in JopSim?

Otherwise this looks fine for me.

Thanks,
Martin

**Comment by torurstrom** [comment]
Ok I will make a new commit on my master branch with the requested changes and a new pull request.

**Comment by torurstrom** [comment]
Ok you can try the merge now. I left the Increment file in Jembench for future synchronization testing, but it is not used by default.

**Comment by schoeberl** [comment]
Mmh, how can I see now the changes? GitHub web does not give me a view on those changes.

Cheers,
Martin

**Comment by jeuneS2** [comment]
Point "Files changed" under the title of the pull request: https://github.com/jop-devel/jop/pull/26/files

**Comment by schoeberl** [comment]
Thanks.

I’ve merged the changes.

Martin

**Pull request merged**
